mybatis:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080
  servlet:
    context-path: /lotteon

spring:
  application:
    name: lotteon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Qwer1234!
    url: jdbc:mysql://3.35.92.212:3306/lotte
    username: team3
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    prefix: classpath:/templates

  # 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: jsa7868@gmail.com
    password: pybwgoacfyleuwje
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true



  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      location: uploads/
      max-file-size: 10MB

  security:
    oauth2:
      client:
        provider:
          kakao:
            # 인가 코드 받기
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            # 토큰 코드 받기
            token-uri: https://kauth.kakao.com/oauth/token
            # 사용자 정보 가져오기
            user-info-uri: https://kapi.kakao.com/v2/user/me
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent

        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code

            # 카카오 > 내 애플리케이션 > 카카오 로그인 > 등록된 Redirect URI 사용
            redirect-uri: http://localhost:8080/sboard/login/oauth2/code/kakao
            client-id: 5d395917afb3f84f1bde6ebcbd12c3cf
            # 카카오 > 내 애플리케이션 > 카카오로그인 > 보안 > Client Secret
            client-secret: 8U4ZM3EKyAlXR3BDQ3wpaozimhKNE4Nt
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image

          google:
            client-id: 798155618029-5l08jbeia24v5k5jvq605sojv2uml6os.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/farmstory/login/oauth2/code/google
            scope:
              - email
              - profile

pagehelper:
  helper-dialect: mysql
  reasonable: true

# 파일 업로드 설정
file:
  upload:
    path: uploads/


img:
  upload:
    path: src/main/resources/static/product


logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace